version: '3'

services:
  app:
    build: .
    restart: always
    env_file: .env
    ports:
      - "${EXT_PORT}:80"
    volumes:
      - ./data/media:/app/media
    depends_on:
      - postgres
    links:
      - postgres
    logging: &logging
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    environment:
      PRODUCTION_ENV: 1
  postgres:
    image: postgres:10.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${POSTGRES_EXT_PORT}:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    logging: *logging

