version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: ./django_dev/Dockerfile
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
      - "8888:8888"
      - "80:80"
    volumes:
      - ./project:/app

    depends_on:
      - postgres
    links:
      - postgres
    entrypoint:
      - /entrypoint.sh

  postgres:
    image: postgres:10.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data

