# Generated by Django 2.0.3 on 2018-03-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_propertyimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
    ]
