# Generated by Django 2.0.3 on 2018-03-21 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20180321_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
