# Generated by Django 2.0.3 on 2018-03-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20180330_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='property_field',
            new_name='profile',
        ),
    ]
