# Generated by Django 2.0.3 on 2018-03-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20180330_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyImage',
            new_name='ProfileImage',
        ),
    ]
