# Generated by Django 2.0.3 on 2018-04-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_profile_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
