# Generated by Django 2.0.3 on 2018-04-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_profile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='image',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.Profile'),
        ),
    ]
