# Generated by Django 2.0.3 on 2018-04-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20180402_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.SmallIntegerField(choices=[('На модерации', 0), ('В конкурсе', 1)], default=1, verbose_name='Статус'),
        ),
    ]
