# Generated by Django 2.0.3 on 2018-04-02 20:49

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20180402_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=content.models.generate_file_name, verbose_name='Юзерпик'),
        ),
    ]
