# Generated by Django 2.0.4 on 2018-04-03 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20180403_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_vote_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего голосования'),
        ),
    ]
